### ISSUE TITLE
Grouping or Tagging

### ISSUE THREAD

**Issue by helmbold** [kotlintest/kotlintest#14]
Sometimes you want to execute only certain tests. Something like ScalaTest's [Tagging](http://www.scalatest.org/user_guide/tagging_your_tests) or TestNG's [Groups](http://testng.org/doc/documentation-main.html#test-groups), preferably with [exclusion](http://testng.org/doc/documentation-main.html#exclusions) would be handy.

**Comment by sksamuel** [comment]
Scalatest has the advantage of refined types. In kotlin might have to be an
annotation.

**Comment by helmbold** [comment]
I don't think annotations are necessary. What do you think about this:

```kotlin
"ListStack.pop" should "return the last element from stack" tagged "db" {
    ...
}

"ListStack.pop" should "return the last element from stack".tagged("db", "order") {
    ...
}
```

I think each testing style would need a different way to add tags.

**Comment by sksamuel** [comment]
Yes i think that would work. Depends on precedence. Would have to test

**Comment by helmbold** [comment]
Or maybe something like this, a bit unconvential at first, but tags on web pages are at the bottom in many cases:

```kotlin
"ListStack.pop" should "return the last element from stack" {
    ...
}.tagged("db", "order")
```

Maybe it would be good to have some more opinions ...

**Comment by sksamuel** [comment]
yep but not sure how many people read these things :)

**Comment by helmbold** [comment]
Maybe you could sketch some variants and ask for opinions on [reddit](https://www.reddit.com/r/kotlin) or [discuss.kotlinlang.org](https://discuss.kotlinlang.org/).

However I think adding such meta data as tags is an important step in the API design since more meta (like `times`, `timeout` etc.) data could be added later. And if the design is not good at this point the API gets broken. So I think it is worth to think some time about the design and possible future extensions.

```kotlin
"ListStack.pop" should "return the last element from stack".tagged("db", "order").times(5).threads(5).timeout(100) {
   ...
}

"ListStack.pop" should "return the last element from stack" {
   ...
}
.tagged("db", "order")
.times(5)
.threads(5)
.timeout(100)
```

In principle a test is like a builder building the test, and adding some meta data in my examples.

**Comment by helmbold** [comment]
I've collected some examples about possible extensions from JUnit and TestNG. This could serve as a guide when designing the API for things like grouping/tagging, timeouts, threads and so on. 

**JUnit**

* [Ignore](https://github.com/junit-team/junit4/wiki/Ignoring-tests): `@Ignore("Test is ignored as a demonstration")`
* [Timeout](https://github.com/junit-team/junit4/wiki/Timeout-for-tests): `@Test(timeout=1000)`, for all tests in a class `@Rule public Timeout globalTimeout = Timeout.seconds(10);`
* [Rules](https://github.com/junit-team/junit4/wiki/Rules)
* [Runners](https://github.com/junit-team/junit4/wiki/Test-runners)
* [Categories](https://github.com/junit-team/junit4/wiki/Categories) (similar to groups, tags)

**TestNG**

* [Groups](http://testng.org/doc/documentation-main.html#test-groups), `@Test(groups = { "functest", "checkintest" })`
* [Groups of Groups](http://testng.org/doc/documentation-main.html#groups-of-groups)
  ```
  <groups>
    <define name="functest">
      <include name="windows"/>
      <include name="linux"/>
    </define>
  
    <define name="all">
      <include name="functest"/>
      <include name="checkintest"/>
    </define>
  
    <run>
      <include name="all"/>
    </run>
  </groups>
  ```
* [Exclusion Groups](http://testng.org/doc/documentation-main.html#exclusions)
  ```
  <run>
      <include name="checkintest"/>
      <exclude name="broken"/>
  </run>
  ```
* [Dependencies](http://testng.org/doc/documentation-main.html#dependent-methods) (between tests), `@Test(dependsOnMethods = { "serverStartedOk" })`. I'm not sure wheter this is a good idea ...
* [Parallelism and time-outs](http://testng.org/doc/documentation-main.html#parallel-running), `@Test(threadPoolSize = 3, invocationCount = 10,  timeOut = 10000)`
* [Interceptors](http://testng.org/doc/documentation-main.html#methodinterceptors)
* [Listener](http://testng.org/doc/documentation-main.html#testng-listeners)
* [Dependency injection](http://testng.org/doc/documentation-main.html#dependency-injection)

**Comment by sksamuel** [comment]
Thanks for the links. I think that the builder pattern trailing after the test is what I prefer personally, but I'll explore and see what we can do with overloads.

```kotlin
"my test" should "do this" {
  // test
} tagged "foo" timeout 1500
```

```kotlin
should("do this") {
  // test
} tagged "foo" timeout 1500
```

```kotlin
"my test" should {
  "do this" {
    // test
  } tagged "foo" timeout 1500
}
```

**Comment by helmbold** [comment]
I prefer the usual method style, since it is easier to see the key-value pairs then. 

```
tagged "foo" timeout 1500
tagged("foo").timout(1500)
```

In principle it would be possible to have a single method and use named params instead:

```kotlin
"my test" should "do this" {
  // test
}.meta(tag = "foo", timeout = 1500, threads = 5, invocationCount = 10)

I'm not sure whether `meta` is a good name, but the approach is pretty simple and readable, I think.

**Comment by sksamuel** [comment]
Have a look at that PR I created and see if you think it looks about right.
I can't get `FlatSpec` to work with the params method at the moment, the DSL doesn't want to like it, but I'll address that later.

**Comment by helmbold** [comment]
It looks good! I thought some time about whether `ignored` should be a separate method or not, but I think it is better like it is. In the end `ignored` is just some kind of meta-data like `tags` or `threads`. And I definitely like the simplicity and clarity of the approach. 

Another thing I'm wondering about is the name `params`. It is short and easy to remember and I like it, but it could be confused with test parametrization (like with generators or tables). But I think params is a bit better than `meta` and I have no other good suggestion. I thought about `config`, but something like `tags` is not exactly configuration of a test case. Maybe `attributes` or `properties`? In [Java EE Servlet terms](http://stackoverflow.com/questions/5243754/difference-between-getattribute-and-getparameter) a parameter is something coming in from the outside, whereas an attribute is something added to a request on the server side. This could be a meaningful in our context, too, since the `params` are not passed to the test directly. See [attribute vs property](http://english.stackexchange.com/questions/28085/what-is-the-difference-between-attribute-and-property).

```kotlin
scenario("support threads parameter") {
        Thread.sleep(1000)
        theadCounter.incrementAndGet()
}.attributes(timeout = 10000, threads = 100, invocations = 100)

// vs

scenario("support threads parameter") {
        Thread.sleep(1000)
        theadCounter.incrementAndGet()
}.properties(timeout = 10000, threads = 100, invocations = 100)
```

However, I was not able to execute your tests, but maybe that is related to the FlatSpec thing.

**Comment by sksamuel** [comment]
What couldn't you execute? Just checking it out and gradle test ? Instead
of params what about props?

**Comment by helmbold** [comment]
My favorite would be `attributes`, since I think (as a non-native speaker) it would be the most precise term in this case and cannot be confused with something else (like `params` or `properties`). To cite the [discussion](http://english.stackexchange.com/questions/28085/what-is-the-difference-between-attribute-and-property) linked above: "Attributes and properties are the same, however, attribute of something is given by people and property is something the a things naturally possess." Since `attributes` and `properties` are so similar I could also live with the latter. However I'd prefer `properties` to `props`. Akka uses `props` and somehow I never liked it.

If I run `gradle test` I get the following error:

```
> gradle test
:compileKotlin
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestKotlin
e: java.lang.IndexOutOfBoundsException: Index 0 is out of bound of empty list.
        at kotlin.collections.EmptyList.get(Collections.kt:29)
        at kotlin.collections.EmptyList.get(Collections.kt:19)
        at org.jetbrains.kotlin.types.TypeSubstitutor.substituteTypeArguments(TypeSubstitutor.java:241)
        at org.jetbrains.kotlin.types.TypeSubstitutor.substituteCompoundType(TypeSubstitutor.java:227)
        at org.jetbrains.kotlin.types.TypeSubstitutor.unsafeSubstitute(TypeSubstitutor.java:201)
        at org.jetbrains.kotlin.types.TypeSubstitutor.substituteWithoutApproximation(TypeSubstitutor.java:121)
        at org.jetbrains.kotlin.types.TypeSubstitutor.substitute(TypeSubstitutor.java:106)
        at org.jetbrains.kotlin.types.TypeSubstitutor.substitute(TypeSubstitutor.java:100)
        at org.jetbrains.kotlin.descriptors.impl.FunctionDescriptorImpl.getSubstitutedValueParameters(FunctionDescriptor
Impl.java:596)
        at org.jetbrains.kotlin.descriptors.impl.FunctionDescriptorImpl.doSubstitute(FunctionDescriptorImpl.java:502)
        at org.jetbrains.kotlin.descriptors.impl.FunctionDescriptorImpl$CopyConfiguration.build(FunctionDescriptorImpl.j
ava:427)
        at org.jetbrains.kotlin.descriptors.impl.SimpleFunctionDescriptorImpl.copy(SimpleFunctionDescriptorImpl.java:103
)
        at org.jetbrains.kotlin.descriptors.impl.SimpleFunctionDescriptorImpl.copy(SimpleFunctionDescriptorImpl.java:28)

        at org.jetbrains.kotlin.resolve.OverridingUtil.createAndBindFakeOverride(OverridingUtil.java:541)
        at org.jetbrains.kotlin.resolve.OverridingUtil.createAndBindFakeOverrides(OverridingUtil.java:385)
        at org.jetbrains.kotlin.resolve.OverridingUtil.generateOverridesInFunctionGroup(OverridingUtil.java:326)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassM
emberScope.generateFakeOverrides(DeserializedClassDescriptor.kt:223)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassM
emberScope.computeNonDeclaredFunctions(DeserializedClassDescriptor.kt:210)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedMemberScope.computeFunctions(Deser
ializedMemberScope.kt:74)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedMemberScope.access$computeFunction
s(DeserializedMemberScope.kt:33)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedMemberScope$functions$1.invoke(Des
erializedMemberScope.kt:51)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedMemberScope$functions$1.invoke(Des
erializedMemberScope.kt:33)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.
java:394)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorag
eManager.java:458)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedMemberScope.getContributedFunction
s(DeserializedMemberScope.kt:83)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassM
emberScope.computeNonDeclaredFunctions(DeserializedClassDescriptor.kt:208)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedMemberScope.computeFunctions(Deser
ializedMemberScope.kt:74)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedMemberScope.access$computeFunction
s(DeserializedMemberScope.kt:33)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedMemberScope$functions$1.invoke(Des
erializedMemberScope.kt:51)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedMemberScope$functions$1.invoke(Des
erializedMemberScope.kt:33)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.
java:394)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorag
eManager.java:458)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedMemberScope.getContributedFunction
s(DeserializedMemberScope.kt:83)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassM
emberScope.computeNonDeclaredFunctions(DeserializedClassDescriptor.kt:208)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedMemberScope.computeFunctions(Deser
ializedMemberScope.kt:74)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedMemberScope.access$computeFunction
s(DeserializedMemberScope.kt:33)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedMemberScope$functions$1.invoke(Des
erializedMemberScope.kt:51)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedMemberScope$functions$1.invoke(Des
erializedMemberScope.kt:33)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.
java:394)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorag
eManager.java:458)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedMemberScope.getContributedFunction
s(DeserializedMemberScope.kt:83)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedMemberScope$addFunctionsAndPropert
ies$2.invoke(DeserializedMemberScope.kt:152)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedMemberScope$addFunctionsAndPropert
ies$2.invoke(DeserializedMemberScope.kt:33)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedMemberScope.addMembers(Deserialize
dMemberScope.kt:163)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedMemberScope.addFunctionsAndPropert
ies(DeserializedMemberScope.kt:152)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedMemberScope.computeDescriptors(Des
erializedMemberScope.kt:128)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassM
emberScope$allDescriptors$1.invoke(DeserializedClassDescriptor.kt:199)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassM
emberScope$allDescriptors$1.invoke(DeserializedClassDescriptor.kt:196)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:3
21)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager
.java:362)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassM
emberScope.getContributedDescriptors(DeserializedClassDescriptor.kt:203)
        at org.jetbrains.kotlin.resolve.scopes.ResolutionScope$DefaultImpls.getContributedDescriptors$default(Resolution
Scope.kt:37)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassMemberScope.computeExtraDescriptors(LazyClassMemberSco
pe.kt:70)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassMemberScope$extraDescriptors$1.invoke(LazyClassMemberS
cope.kt:57)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassMemberScope$extraDescriptors$1.invoke(LazyClassMemberS
cope.kt:46)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:3
21)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager
.java:362)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassMemberScope.getContributedDescriptors(LazyClassMemberS
cope.kt:63)
        at org.jetbrains.kotlin.resolve.DescriptorUtils.getAllDescriptors(DescriptorUtils.java:558)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassDescriptor.resolveMemberHeaders(LazyClassDescriptor.ja
va:569)
        at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer.resolveAllHeadersInClasses(LazyTopDownAnalyzer.kt:199)
        at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer.analyzeDeclarations(LazyTopDownAnalyzer.kt:179)
        at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzerForTopLevel.analyzeDeclarations(LazyTopDownAnalyzerForTopLeve
l.java:74)
        at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzerForTopLevel.analyzeFiles(LazyTopDownAnalyzerForTopLevel.java:
66)
        at org.jetbrains.kotlin.resolve.jvm.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerF
acadeForJVM.java:145)
        at org.jetbrains.kotlin.resolve.jvm.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegrationWithCustomContext
(TopDownAnalyzerFacadeForJVM.java:78)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.analyze(KotlinToJVMBytecodeCompil
er.kt:290)
        at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerRepo
rt.kt:129)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:283)

        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyzeAndGenerate(KotlinToJVMBytecodeCompi
ler.kt:269)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileBunchOfSources(KotlinToJVMBytecodeCo
mpiler.kt:194)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:196)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:49)
        at org.jetbrains.kotlin.cli.common.CLICompiler.exec(CLICompiler.java:181)
        at org.jetbrains.kotlin.gradle.tasks.AbstractKotlinCompile.callCompiler(Tasks.kt:87)
        at org.jetbrains.kotlin.gradle.tasks.AbstractKotlinCompile.compile(Tasks.kt:63)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(Anno
tationProcessingTaskFactory.java:228)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(Annota
tionProcessingTaskFactory.java:221)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(Annota
tionProcessingTaskFactory.java:210)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.j
ava:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.
java:61)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46
)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskEx
ecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:68)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExec
uter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.j
ava:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.j
ava:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecute
r.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecute
r.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecut
or.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:
50)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter
.java:94)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExe
cuter.java:51)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExe
cuter.java:28)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:24
1)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:21
4)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:207)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)

:compileTestKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileTestKotlin'.
> Internal compiler error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by sksamuel** [comment]
That looks like a bug in kotlin or gradle. It works for me `gradle clean test` and the only methods in the stack trace are in gradle, kotlin and java classes. Are you on a recent gradle build?

`attributes` is ok, its just a bit annoying to type. As a native English speaker, I don't think there's much difference between attributes and properties. People just use them interchangeably. 

So we've got

`properties`
`props`
`config`
`params`
`attributes`

(I know what you are saying about props in akka. I don't like that either, but I think that's more because its really an odd name for what is "Actor Create Function". The `props` is just used to capture the case class apply method.)

**Comment by helmbold** [comment]
I don't think that `attributes` (still  my favorite) or `properties` are annoying to type, since most programmers are using code completion anyway. And at least to me a complete word looks better than an abbreviation like `props`.

But to come to my build issue: Gradle -version shows this:

```
> gradle -version

------------------------------------------------------------
Gradle 2.13
------------------------------------------------------------

Build time:   2016-04-25 04:10:10 UTC
Build number: none
Revision:     3b427b1481e46232107303c90be7b05079b05b1c

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_91 (Oracle Corporation 25.91-b14)
OS:           Windows 10 10.0 amd64
```

**Comment by sksamuel** [comment]
sam@sam-xubuntu:~/development/workspace/kotlintest$ gradle -version

------------------------------------------------------------
Gradle 2.3
------------------------------------------------------------

Build time:   2015-02-16 05:09:33 UTC
Build number: none
Revision:     586be72bf6e3df1ee7676d1f2a3afd9157341274

Groovy:       2.3.9
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_45 (Oracle Corporation 25.45-b02)
OS:           Linux 3.19.0-15-generic amd64

sam@sam-xubuntu:~/development/workspace/kotlintest$ gradle clean test
:clean
:compileKotlin
:compileJava UP-TO-DATE
:processResources
:classes
:compileTestKotlin
w:
/home/sam/development/workspace/kotlintest/src/test/kotlin/io/kotlintest/TableChecksTest.kt:
(19, 13): Variable 'inputs' is never used
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test

BUILD SUCCESSFUL

Total time: 21.098 secs

**Comment by helmbold** [comment]
Thanks. It looks like a compiler bug:

```
* What went wrong:
Execution failed for task ':compileTestKotlin'.
> Internal compiler error. See log for more details
```

I've tried to bump the Kotlin versions
```
buildscript {
    ext.kotlin_version = '1.0.2'
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.0.2'
    }
}

...
dependencies {
    compile 'org.jetbrains.kotlin:kotlin-stdlib:1.0.2'
    compile 'org.jetbrains.kotlin:kotlin-reflect:1.0.2'
}
```

But I get the same error.

**Comment by sksamuel** [comment]
Might be something on windows, that's the main difference between my setup
and yours. Perhaps you should raise a ticket with jetbrains.

**Comment by sksamuel** [comment]
Other than changing the word from params, its basically ready to merge.

**Comment by helmbold** [comment]
I've just realized that [TestNG](http://testng.org/doc/documentation-main.html#annotations) and [JUnit5](http://junit.org/junit5/docs/current/user-guide/#disabling-tests) both use `enabled` (or `@Disabled` in the case of JUnit) instead of `ignored`. Maybe we should adopt this convention and rename `ignored` to `enabled`.

**Comment by sksamuel** [comment]
enabled=false in the config block then

**Comment by sksamuel** [comment]
I think I like `config` in the end. It's short, its pretty generic (like all these words are), and you type it often enough that you don't have to think about it. Wdyt

**Comment by helmbold** [comment]
`config` is fine and pretty much self explaing – it is the configuration of the thing it is appended to, a test case in our case.

**Comment by sksamuel** [comment]
I will update and merge and release 2.0 with the table tests and tolerance.

**Comment by sksamuel** [comment]
1.2 even
