### ISSUE TITLE
Some external event-aware libraries failing due to incorrect Description instance for JUnit

### ISSUE THREAD

**Issue by saksmt** [kotlintest/kotlintest#140]
When creating new instance of `Description` class name seems to be not real one (`javaClass.simpleName` for name of the suite which is used as class name for test cases), so when attempting to `desription.getTestClass()`returns null when it is not expected resulting in loud crash of the whole JUnit.

Example of library heavily depending on events: [Allure](https://github.com/allure-framework/allure1)

Example of error:

```
[ERROR] org.apache.maven.surefire.testset.TestSetFailedException: java.lang.NullPointerException
[ERROR] at org.apache.maven.surefire.common.junit4.JUnit4RunListener.rethrowAnyTestMechanismFailures(JUnit4RunListener.java:209)
[ERROR] at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:169)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
[ERROR] Caused by: java.lang.NullPointerException
[ERROR] at org.junit.runner.Description.createSuiteDescription(Description.java:124)
[ERROR] at ru.yandex.qatools.allure.junit.AllureRunListener.getSuiteUid(AllureRunListener.java:110)
[ERROR] at ru.yandex.qatools.allure.junit.AllureRunListener.testStarted(AllureRunListener.java:50)
[ERROR] at org.junit.runner.notification.SynchronizedRunListener.testStarted(SynchronizedRunListener.java:49)
[ERROR] at org.junit.runner.notification.RunNotifier$3.notifyListener(RunNotifier.java:121)
[ERROR] at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
[ERROR] at org.junit.runner.notification.RunNotifier.fireTestStarted(RunNotifier.java:118)
[ERROR] at org.apache.maven.surefire.common.junit4.Notifier.fireTestStarted(Notifier.java:100)
[ERROR] at io.kotlintest.TestBase.runTest(TestBase.kt:119)
[ERROR] at io.kotlintest.TestBase.runSharedInstance(TestBase.kt:104)
[ERROR] at io.kotlintest.TestBase.run$kotlintest_compileKotlin(TestBase.kt:43)
[ERROR] at io.kotlintest.KTestJUnitRunner.run(KTestJUnitRunner.kt:14)
[ERROR] at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
[ERROR] at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
[ERROR] at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
[ERROR] at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
[ERROR] ... 3 more
```

Affected lines in allure:

```java
return new Description(testClass, testClass.getName(), testClass.getAnnotations()); // org.junit.runner.Description#createSuiteDescription(): 124
///////////////////////////////////////////////////////////////////////////////////
Description suiteDescription = Description.createSuiteDescription(description.getTestClass()); // ru.yandex.qatools.allure.junit.AllureRunListener#getSuiteId(): 110
///////////////////////////////////////////////////////////////////////////////////
TestCaseStartedEvent event = new TestCaseStartedEvent(this.getSuiteUid(description), description.getMethodName()); // ru.yandex.qatools.allure.junit.AllureRunListener#testStarted(): 50
```

**Comment by sksamuel** [comment]
I'm not sure how frameworks like this work with things like kotlintest or scalatest which are much richer in the way they create descriptions. Looking at the description documentation it doesn't say that a description _has_ to be a class and method.
