### ISSUE TITLE
Reflections exception thrown on test startup

### ISSUE THREAD

**Issue by Hyperparticle** [kotlintest/kotlintest#183]
When I run my tests in IntelliJ `2017.1.3` on Linux, I get this output:

```
[main] WARN org.reflections.Reflections - could not create Vfs.Dir from url. ignoring the exception and continuing
org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/libatk-wrapper.so]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:109)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:91)
	at org.reflections.Reflections.scan(Reflections.java:237)
	at org.reflections.Reflections.scan(Reflections.java:204)
	at org.reflections.Reflections.<init>(Reflections.java:129)
	at org.reflections.Reflections.<init>(Reflections.java:170)
	at io.kotlintest.Project.<init>(Project.kt:13)
	at io.kotlintest.Project.<clinit>(Project.kt:6)
	at io.kotlintest.Spec.run$kotlintest_main(Spec.kt:45)
	at io.kotlintest.KTestJUnitRunner.run(KTestJUnitRunner.kt:14)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
[main] INFO org.reflections.Reflections - Reflections took 1734 ms to scan 85 urls, producing 7827 keys and 41046 values 
```

This doesn't show up when I run `gradle test`, so maybe it's specific to the JUnit test runner in IntelliJ, but the exception still originates from kotlintest. Downgrading to `1.3.7` removes this error, and using any of `2.0.x` causes this message to reappear.

**Comment by sksamuel** [comment]
Seems to be a mac only thing (which I don't have) but I've implement a fix I've found online. Will be in the next release. Please reopen if still occurs.

**Comment by sschuberth** [comment]
> Seems to be a mac only thing

For the record, no, it's not. I was also seeing this on Windows. See the related https://github.com/ronmamo/reflections/issues/80.

**Comment by sksamuel** [comment]
That's the thread I read, but thanks for letting me know (I use linux, haven't seen it). I'm about to release next version of KotlinTest so hopefully the fix I added will go make this issue go away.

**Comment by sksamuel** [comment]
2.0.6 is out.

**Comment by stoyle** [comment]
Hi! On kotlintest 2.0.7 and running gradle, and seeing the same issue. Just updated to High Sierra, so I believe that may be the issue. I think the error is in reflections as ronmamo/reflections#80 states. But if there is anything that can be done here, that would be great. 

Be happy to help if you point i the right direction as well.

Cheers,
Alf

**Comment by dansanduleac** [comment]
I'm having the same issue on windows with 1.2.20 (1.2.10 as well), also on latest 2.0.7.

**Comment by shpychka** [comment]
hey! Have the same issue on mac and linux, using kotlintest 2.0.7 version. Please, re-open

**Comment by piotrturski** [comment]
same for ubuntu 14.04, java 9, kotlintest:2.0.7, kotlin 1.2.21

**Comment by dmcollie** [comment]
I had the same problem when running on KotlinTest 2.0.0. I changed the version to 2.0.7 and have a different set of errors on test startup. I'm running the tests through IDEA using the Unit test runner. MacOS High Sierra.

```
er.main(JUnitStarter.java:70)
Caused by: org.reflections.ReflectionsException: could not create class file from MANIFEST.MF
	at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:102)
	at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:24)
	at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:30)
	... 22 common frames omitted
Caused by: java.io.IOException: bad magic number: 4d616e69
	at javassist.bytecode.ClassFile.read(ClassFile.java:825)
	at javassist.bytecode.ClassFile.<init>(ClassFile.java:154)
	at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:100)
	... 24 common frames omitted
10:12:43.047 [main] DEBUG org.reflections.Reflections - could not scan file META-INF/MANIFEST.MF in url file:/Users/dave/.m2/repository/org/springframework/spring-test/5.0.4.RELEASE/spring-test-5.0.4.RELEASE.jar with scanner SubTypesScanner
org.reflections.ReflectionsException: could not create class object from file META-INF/MANIFEST.MF
	at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:32)
	at org.reflections.Reflections.scan(Reflections.java:253)
	at org.reflections.Reflections.scan(Reflections.java:202)
	at org.reflections.Reflections.<init>(Reflections.java:123)
	at org.reflections.Reflections.<init>(Reflections.java:168)
	at io.kotlintest.Project.discoverProjectConfig(Project.kt:15)
	at io.kotlintest.Project.<init>(Project.kt:27)
	at io.kotlintest.Project.<clinit>(Project.kt:8)
	at io.kotlintest.KTestJUnitRunner.<init>(KTestJUnitRunner.kt:10)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.reflections.ReflectionsException: could not create class file from MANIFEST.MF
	at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:102)
	at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:24)
	at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:30)
	... 22 common frames omitted
Caused by: java.io.IOException: bad magic number: 4d616e69
	at javassist.bytecode.ClassFile.read(ClassFile.java:825)
	at javassist.bytecode.ClassFile.<init>(ClassFile.java:154)
	at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:100)
	... 24 common frames omitted
```

**Comment by Phaestion** [comment]
Same issue here on an Ubuntu 16.04 machine on Kotlintest 2.0.7.

**Comment by bondpp7** [comment]
Same here on Windows 7, kotlintest 3.0.0-RC2

**Comment by sksamuel** [comment]
3.0.0-RC3 should be fixed. I have tested it on travis, locally, windows and linux and after the latest fixes I don't see this error anymore.
