### ISSUE TITLE
Reflection scan startup cost

### ISSUE THREAD

**Issue by ScottPeterJohnson** [kotlintest/kotlintest#219]
As part of project configuration, kotlintest will use the Reflections library to scan the _entire_ classpath for instances of ProjectConfig.
If I'm running a single test, this imposes a very annoying 2.5 second startup cost that there's no way around.
Could we get either:
1. Some way of prespecifying a (nullable) Project config to use so the scan is skipped?
2. Some way to configure the scan and restrict its scope? (System properties would be standard)

**Comment by sksamuel** [comment]
Something like `-DprojectConfigScan=false` ?
Could add that.

**Comment by eric239** [comment]
@sksamuel will you please add such a property?
Besides the start up time reported by @ScottPeterJohnson, my default logback configuration is somehow (can't trace why) has `debug` logging at the root level, and so I get gazillion messages like this
```
17:52:38.050 [main] DEBUG org.reflections.Reflections - could not scan file com/oracle/tools/packager/linux/template.copyright in url file:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/lib/ant-javafx.jar with scanner TypeAnnotationsScanner
org.reflections.ReflectionsException: could not create class object from file com/oracle/tools/packager/linux/template.copyright
	at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:32)
	at org.reflections.Reflections.scan(Reflections.java:253)
	at org.reflections.Reflections.scan(Reflections.java:202)
	at org.reflections.Reflections.<init>(Reflections.java:123)
	at org.reflections.Reflections.<init>(Reflections.java:168)
	at io.kotlintest.Project.<init>(Project.kt:17)
	at io.kotlintest.Project.<clinit>(Project.kt:8)
	at io.kotlintest.KTestJUnitRunner.<init>(KTestJUnitRunner.kt:10)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.reflections.ReflectionsException: could not create class file from template.copyright
....
```
and of course all my attempts to reset the logging level are futile as reflections scan happens very early in KotlinTest initialization.

**Comment by eric239** [comment]
Thanks for the quick commit!
