### ISSUE TITLE
Can't generate allure report

### ISSUE THREAD

**Issue by zaz600** [kotlintest/kotlintest#415]
Hello.

I'm trying build project with allure support and i have the exceptions during gradle test command

source https://gist.github.com/zaz600/54caf834b43636c4b07d70ee554a358b

Gradle 4.10.1

```
Testing started at 11:40 ...
11:40:39: Executing tasks 'clean test'...

> Task :clean
> Task :compileKotlin NO-SOURCE
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :compileTestKotlin
> Task :compileTestJava NO-SOURCE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :test
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.lang.NoSuchMethodError: io.kotlintest.TestResult.getMetaData()Ljava/util/List;
	at io.kotlintest.extensions.allure.AllureExtension$afterTest$1.accept(AllureExtension.kt:55)
	at io.kotlintest.extensions.allure.AllureExtension$afterTest$1.accept(AllureExtension.kt:14)
	at io.qameta.allure.AllureLifecycle.lambda$updateTestCase$10(AllureLifecycle.java:178)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.qameta.allure.AllureLifecycle.updateTestCase(AllureLifecycle.java:176)
	at io.kotlintest.extensions.allure.AllureExtension.afterTest(AllureExtension.kt:46)
	at io.kotlintest.runner.jvm.TestCaseExecutor$execute$2.invoke(TestCaseExecutor.kt:35)
	at io.kotlintest.runner.jvm.TestCaseExecutor$execute$4.invoke(TestCaseExecutor.kt:54)
	at io.kotlintest.runner.jvm.TestCaseExecutor$execute$4.invoke(TestCaseExecutor.kt:17)
	at io.kotlintest.runner.jvm.TestCaseExecutor$execute$3.invoke(TestCaseExecutor.kt:45)
	at io.kotlintest.runner.jvm.TestCaseExecutor.execute(TestCaseExecutor.kt:54)
	at io.kotlintest.runner.jvm.SharedInstanceSpecRunner$callingThreadContext$1.registerTestCase(SharedInstanceSpecRunner.kt:29)
	at io.kotlintest.TestContext.registerTestCase(TestContext.kt:41)
	at io.kotlintest.specs.AbstractWordSpec$WordScope.invoke(AbstractWordSpec.kt:54)
	at AllureTest$1.invoke(AllureTest.kt:14)
	at AllureTest$1.invoke(AllureTest.kt:7)
	at io.kotlintest.specs.AbstractWordSpec$should$1.invoke(AbstractWordSpec.kt:30)
	at io.kotlintest.specs.AbstractWordSpec$should$1.invoke(AbstractWordSpec.kt:23)
	at io.kotlintest.runner.jvm.TestCaseExecutor$executeTestSet$1.run(TestCaseExecutor.kt:96)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NoSuchMethodError: io.kotlintest.TestResult.getMetaData()Ljava/util/List;
	at io.kotlintest.extensions.allure.AllureExtension$afterTest$1.accept(AllureExtension.kt:55)
	at io.kotlintest.extensions.allure.AllureExtension$afterTest$1.accept(AllureExtension.kt:14)
	at io.qameta.allure.AllureLifecycle.lambda$updateTestCase$10(AllureLifecycle.java:178)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.qameta.allure.AllureLifecycle.updateTestCase(AllureLifecycle.java:176)
	at io.kotlintest.extensions.allure.AllureExtension.afterTest(AllureExtension.kt:46)
	at io.kotlintest.runner.jvm.TestCaseExecutor$execute$2.invoke(TestCaseExecutor.kt:35)
	at io.kotlintest.runner.jvm.TestCaseExecutor$execute$4.invoke(TestCaseExecutor.kt:54)
	at io.kotlintest.runner.jvm.TestCaseExecutor$execute$4.invoke(TestCaseExecutor.kt:17)
	at io.kotlintest.runner.jvm.TestCaseExecutor$execute$3.invoke(TestCaseExecutor.kt:45)
	at io.kotlintest.runner.jvm.TestCaseExecutor.execute(TestCaseExecutor.kt:54)
	at io.kotlintest.runner.jvm.SharedInstanceSpecRunner$execute$1.invoke(SharedInstanceSpecRunner.kt:14)
	at io.kotlintest.runner.jvm.SharedInstanceSpecRunner$execute$1.invoke(SharedInstanceSpecRunner.kt:8)
	at io.kotlintest.runner.jvm.SpecRunner$interceptSpec$chain$1.invoke(SpecRunner.kt:36)
	at io.kotlintest.runner.jvm.SpecRunner$interceptSpec$chain$1.invoke(SpecRunner.kt:11)
	at io.kotlintest.runner.jvm.SpecRunner.interceptSpec(SpecRunner.kt:37)
	at io.kotlintest.runner.jvm.SharedInstanceSpecRunner.execute(SharedInstanceSpecRunner.kt:11)
	at io.kotlintest.runner.jvm.TestEngine.executeSpec(TestEngine.kt:109)
	at io.kotlintest.runner.jvm.TestEngine.access$executeSpec(TestEngine.kt:14)
	at io.kotlintest.runner.jvm.TestEngine$submitSpec$1.run(TestEngine.kt:89)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NoSuchMethodError: io.kotlintest.TestResult.getMetaData()Ljava/util/List;
	at io.kotlintest.extensions.allure.AllureExtension$afterTest$1.accept(AllureExtension.kt:55)
	at io.kotlintest.extensions.allure.AllureExtension$afterTest$1.accept(AllureExtension.kt:14)
	at io.qameta.allure.AllureLifecycle.lambda$updateTestCase$10(AllureLifecycle.java:178)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.qameta.allure.AllureLifecycle.updateTestCase(AllureLifecycle.java:176)
	at io.kotlintest.extensions.allure.AllureExtension.afterTest(AllureExtension.kt:46)
	at io.kotlintest.runner.jvm.TestCaseExecutor$execute$2.invoke(TestCaseExecutor.kt:35)
	at io.kotlintest.runner.jvm.TestCaseExecutor$execute$4.invoke(TestCaseExecutor.kt:54)
	at io.kotlintest.runner.jvm.TestCaseExecutor$execute$4.invoke(TestCaseExecutor.kt:17)
	at io.kotlintest.runner.jvm.TestCaseExecutor$execute$3.invoke(TestCaseExecutor.kt:45)
	at io.kotlintest.runner.jvm.TestCaseExecutor.execute(TestCaseExecutor.kt:54)
	at io.kotlintest.runner.jvm.SharedInstanceSpecRunner$callingThreadContext$1.registerTestCase(SharedInstanceSpecRunner.kt:29)
	at io.kotlintest.TestContext.registerTestCase(TestContext.kt:41)
	at io.kotlintest.specs.AbstractWordSpec$WordScope.invoke(AbstractWordSpec.kt:54)
	at AllureTest$2.invoke(AllureTest.kt:20)
	at AllureTest$2.invoke(AllureTest.kt:7)
	at io.kotlintest.specs.AbstractWordSpec$should$1.invoke(AbstractWordSpec.kt:30)
	at io.kotlintest.specs.AbstractWordSpec$should$1.invoke(AbstractWordSpec.kt:23)
	at io.kotlintest.runner.jvm.TestCaseExecutor$executeTestSet$1.run(TestCaseExecutor.kt:96)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NoSuchMethodError: io.kotlintest.TestResult.getMetaData()Ljava/util/List;
	at io.kotlintest.extensions.allure.AllureExtension$afterTest$1.accept(AllureExtension.kt:55)
	at io.kotlintest.extensions.allure.AllureExtension$afterTest$1.accept(AllureExtension.kt:14)
	at io.qameta.allure.AllureLifecycle.lambda$updateTestCase$10(AllureLifecycle.java:178)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.qameta.allure.AllureLifecycle.updateTestCase(AllureLifecycle.java:176)
	at io.kotlintest.extensions.allure.AllureExtension.afterTest(AllureExtension.kt:46)
	at io.kotlintest.runner.jvm.TestCaseExecutor$execute$2.invoke(TestCaseExecutor.kt:35)
	at io.kotlintest.runner.jvm.TestCaseExecutor$execute$4.invoke(TestCaseExecutor.kt:54)
	at io.kotlintest.runner.jvm.TestCaseExecutor$execute$4.invoke(TestCaseExecutor.kt:17)
	at io.kotlintest.runner.jvm.TestCaseExecutor$execute$3.invoke(TestCaseExecutor.kt:45)
	at io.kotlintest.runner.jvm.TestCaseExecutor.execute(TestCaseExecutor.kt:54)
	at io.kotlintest.runner.jvm.SharedInstanceSpecRunner$execute$1.invoke(SharedInstanceSpecRunner.kt:14)
	at io.kotlintest.runner.jvm.SharedInstanceSpecRunner$execute$1.invoke(SharedInstanceSpecRunner.kt:8)
	at io.kotlintest.runner.jvm.SpecRunner$interceptSpec$chain$1.invoke(SpecRunner.kt:36)
	at io.kotlintest.runner.jvm.SpecRunner$interceptSpec$chain$1.invoke(SpecRunner.kt:11)
	at io.kotlintest.runner.jvm.SpecRunner.interceptSpec(SpecRunner.kt:37)
	at io.kotlintest.runner.jvm.SharedInstanceSpecRunner.execute(SharedInstanceSpecRunner.kt:11)
	at io.kotlintest.runner.jvm.TestEngine.executeSpec(TestEngine.kt:109)
	at io.kotlintest.runner.jvm.TestEngine.access$executeSpec(TestEngine.kt:14)
	at io.kotlintest.runner.jvm.TestEngine$submitSpec$1.run(TestEngine.kt:89)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
BUILD SUCCESSFUL in 2s
3 actionable tasks: 3 executed
11:40:42: Tasks execution finished 'clean test'.
```

**Comment by zaz600** [comment]
sorry, up version to 3.1.10 helped me
